version: "3.8"

services:

  web-server:
    container_name: hectare_frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/app
    ports:
      - "5173:5174"
    command: yarn dev

